version: '3.8'

# LABEL maintainer="Emiliano Rizzonelli <emiliano.rizzonelli@proton.me>"
# LABEL version="1.0"

services:
  backend:
    build: ./backend
    container_name: benchai-backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - benchai-net
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=benchai
      - DB_USER=root
      - DB_PASSWORD=root

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: benchai-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - benchai-net

  mysql:
    image: mysql:8.0
    container_name: benchai-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: benchai
    volumes:
      - benchai-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - benchai-net

networks:
  benchai-net:
    driver: bridge

volumes:
  benchai-mysql-data:
